import Head from 'next/head';
import Image from 'next/image';
import Navigation from '../components/Navigation';
import UserBar from '../components/UserBar';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className="bg-[rgb(15,23,42)] text-white/70 min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navigation />
        <UserBar />
      </div>
    </div>
  );
}
