import Head from 'next/head';
import Image from 'next/image';
import { useAuthState } from 'react-firebase-hooks/auth';
import Navigation from '../components/Navigation';
import UserBar from '../components/UserBar';
import { auth } from '../firebase';
import styles from '../styles/Home.module.css';
import LoginPage from '../components/LoginPage';
export default function Home() {
  const [user, userLoading, userError] = useAuthState(auth);

  return (
    <div className="bg-[rgb(15,23,42)] text-white/70 min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navigation />
        {user ? <UserBar /> : <LoginPage />}
      </div>
    </div>
  );
}
