import Head from 'next/head';
import React from 'react';
import LoginPage from '../components/LoginPage';

function Login() {
  return (
    <div className="h-screen bg-[rgb(15,23,42)] ">
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginPage />
    </div>
  );
}

export default Login;
